import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {openDB,addTrack,editTrack,deleteTrack,tracks,record,addVerifiedTrack,LIMIT_MESSAGE,owned} from '../src/db.js';
import {assess,decide} from '../src/verify.js';import {identify,retailers} from '../src/retailers.js';import {register,login,session,authenticate,recover} from '../src/auth.js';import {tick} from '../src/worker.js';
const expected={retailer:'lisa-gozlan',productId:'123',variantId:'456',seller:'Lisa Gozlan'};
function obs(cents=10000){return {...expected,state:'VERIFIED',cents,currency:'CAD',available:true,title:'Test product',variant:'Black / Medium',method:'fixture',signals:['json-ld','product-json'].map(source=>({...expected,kind:'selling-price',source,currency:'CAD',cents}))};}
function setup(){const db=openDB(':memory:');for(const id of ['alice','bob'])db.prepare('INSERT INTO users(id,email,password,recovery,created) VALUES(?,?,?,?,?)').run(id,id+'@example.com','test','test',1);return db;}
function verified(db,user='alice',o=obs()){const t=addVerifiedTrack(db,user,{url:'https://www.lisagozlan.com/products/br046?variant='+o.variantId},o);record(db,t.productId,o,1000);return t;}
test('15 retailer allowlist entries, Amazon is not advertised supported',()=>{assert.equal(retailers.length,15);assert.equal(identify('https://www.amazon.ca/dp/B012345678').retailer.id,'amazon');});
for(const url of ['http://www.lisagozlan.com/products/x','https://www.lisagozlan.com.evil.test/products/x','https://www.lisagozlan.com@127.0.0.1/products/x','https://127.0.0.1/a','https://www.lisagozlan.com:8443/products/x','https://www.sephora.com/product/x','https://www.ae.com/us/en/p/aerie/x','https://www.lisagozlan.com/products/a%2fb','https://www.lisagozlan.com/products/a\\x','https://us.lisagozlan.com/products/x'])test('reject URL '+url,()=>assert.throws(()=>identify(url)));
test('Aerie is distinguished from American Eagle',()=>assert.equal(identify('https://www.ae.com/ca/en/p/aerie/bras/123').retailer.id,'aerie'));
test('tracking parameters removed, variant retained',()=>assert.equal(identify('https://lisagozlan.com/products/br046?utm_source=mail&variant=123').url,'https://www.lisagozlan.com/products/br046?variant=123'));
for(const [name,change] of [['USD',{currency:'USD'}],['zero',{cents:0}],['negative',{cents:-100}],['NaN',{cents:NaN}],['fractional cents',{cents:100.1}],['wrong product',{productId:'x'}],['wrong variant',{variantId:'x'}],['wrong retailer',{retailer:'amazon'}],['wrong seller',{seller:'other'}],['unavailable',{available:false}],['uncertain',{state:'UNCERTAIN'}],['blocked',{state:'BLOCKED'}],['failed',{state:'FAILED'}]])test('reject '+name,()=>assert.equal(assess(expected,{...obs(),...change}).ok,false));
test('conflicting signals rejected',()=>{const o=obs();o.signals[1].cents=5900;assert.equal(assess(expected,o).ok,false);});
test('financing is not selling price',()=>{const o=obs();o.signals[1].kind='financing';assert.equal(assess(expected,o).ok,false);});
test('baseline established only from verified evidence',()=>{assert.equal(decide(null,null,expected,obs(),1).action,'baseline');assert.equal(decide(null,null,expected,{state:'UNCERTAIN'},1).action,'reject');});
test('drop requires later matching check',()=>{assert.equal(decide(10000,null,expected,obs(7000),1).action,'pending');assert.equal(decide(10000,{cents:7000,at:1},expected,obs(7000),2).action,'pending');assert.equal(decide(10000,{cents:7000,at:1},expected,obs(7000),901).action,'drop');});
test('extreme drop requires two sources and later confirmation',()=>{const o=obs(100);o.signals.pop();assert.equal(decide(10000,{cents:100,at:1},expected,o,901).action,'pending');assert.equal(decide(10000,{cents:100,at:1},expected,obs(100),901).action,'drop');});
test('expired confirmation cannot send alert',()=>assert.equal(decide(10000,{cents:7000,at:1},expected,obs(7000),22000).action,'pending'));
test('limit survives disable, re-enable and direct database writes',()=>{const db=setup(),ids=[];for(let i=0;i<15;i++)ids.push(addTrack(db,'alice',{url:'https://www.lisagozlan.com/products/a'+i}));assert.throws(()=>addTrack(db,'alice',{url:'https://www.lisagozlan.com/products/extra'}),{message:LIMIT_MESSAGE});editTrack(db,'alice',ids[0],{active:false});addTrack(db,'alice',{url:'https://www.lisagozlan.com/products/extra'});assert.throws(()=>editTrack(db,'alice',ids[0],{active:true}),{message:LIMIT_MESSAGE});assert.throws(()=>db.prepare('UPDATE tracks SET active=1 WHERE id=?').run(ids[0]));db.close();});
test('duplicate products prevented and privacy enforced on mutations',()=>{const db=setup(),id=addTrack(db,'alice',{url:'https://www.lisagozlan.com/products/a'});assert.throws(()=>addTrack(db,'alice',{url:'https://www.lisagozlan.com/products/a'}));assert.equal(tracks(db,'bob').length,0);assert.throws(()=>owned(db,'bob',id));assert.throws(()=>editTrack(db,'bob',id,{title:'attack'}));assert.throws(()=>deleteTrack(db,'bob',id));db.close();});
test('unknown never changes verified price; notification dedup and further drops',()=>{const db=setup();db.prepare('UPDATE users SET email_enabled=1').run();const t=verified(db);record(db,t.productId,{state:'FAILED'},2000);assert.equal(tracks(db,'alice')[0].current,10000);assert.equal(db.prepare('SELECT count(*) n FROM activity').get().n,0);record(db,t.productId,obs(7000),3000);record(db,t.productId,obs(7000),4000);record(db,t.productId,obs(7000),5000);assert.equal(db.prepare('SELECT count(*) n FROM activity').get().n,1);assert.equal(db.prepare('SELECT count(*) n FROM outbox').get().n,1);record(db,t.productId,obs(6000),6000);record(db,t.productId,obs(6000),7000);assert.equal(db.prepare('SELECT count(*) n FROM activity').get().n,2);record(db,t.productId,obs(11000),8000);assert.equal(tracks(db,'alice')[0].current,11000);assert.equal(db.prepare('SELECT count(*) n FROM activity').get().n,3);assert.equal(db.prepare('SELECT count(*) n FROM outbox').get().n,2);db.close();});
test('failed check resets a pending drop',()=>{const db=setup(),t=verified(db);record(db,t.productId,obs(7000),2000);record(db,t.productId,{state:'FAILED'},3000);assert.equal(record(db,t.productId,obs(7000),4000).action,'pending');db.close();});
test('disabled products keep history and do not receive new sale activity',()=>{const db=setup(),t=verified(db);editTrack(db,'alice',t.id,{active:false});record(db,t.productId,obs(7000),2000);record(db,t.productId,obs(7000),3000);assert.equal(db.prepare('SELECT count(*) n FROM activity').get().n,0);assert.equal(db.prepare('SELECT count(*) n FROM observations').get().n,3);db.close();});
test('shared variants perform one check; user identities never returned in watchlist',async()=>{const db=setup(),a=verified(db);addVerifiedTrack(db,'bob',{url:'https://www.lisagozlan.com/products/br046?variant=456'},obs());let n=0;db.prepare('UPDATE products SET next_check=0').run();await tick(db,async()=>{n++;return obs();});assert.equal(n,1);assert.ok(!JSON.stringify(tracks(db,'bob')).includes('alice'));db.close();});
test('retailer health trip stops acceptance, other retailer does not trip',()=>{const db=setup();let last;for(let i=0;i<3;i++){const o={...obs(),productId:'p'+i,variantId:'v'+i};o.signals=o.signals.map(s=>({...s,productId:o.productId,variantId:o.variantId}));const t=verified(db,'alice',o);record(db,t.productId,{state:'BLOCKED'},2000);last={t,o};}assert.equal(db.prepare('SELECT state FROM health WHERE retailer=?').get('lisa-gozlan').state,'DEGRADED');assert.equal(record(db,last.t.productId,last.o,2100).action,'reject');assert.equal(db.prepare('SELECT * FROM health WHERE retailer=?').get('gap'),undefined);db.close();});
test('persistent sessions, password hashing and recovery invalidate old sessions',async()=>{const db=openDB(':memory:');const r=await register(db,{email:'test@example.com',password:'very-long-secret-password'});assert.equal(await login(db,{email:'test@example.com',password:'very-long-secret-password'}),r.id);await assert.rejects(login(db,{email:'test@example.com',password:'wrong'}));assert.ok(!db.prepare('SELECT password FROM users').get().password.includes('very-long'));const s=session(db,r.id);assert.equal(authenticate(db,'sw_session='+s.token).user_id,r.id);const next=await recover(db,{email:'test@example.com',password:'another-secret-password',recovery:r.recovery});assert.notEqual(next.recovery,r.recovery);assert.equal(authenticate(db,'sw_session='+s.token),null);await assert.rejects(recover(db,{email:'test@example.com',password:'another-secret-password',recovery:r.recovery}));db.close();});
test('new subscriber reuses only latest shared observation, not another user history',()=>{const db=setup(),a=verified(db);record(db,a.productId,obs(12000),2000);record(db,a.productId,obs(13000),3000);const b=addVerifiedTrack(db,'bob',{url:'https://www.lisagozlan.com/products/br046?variant=456'},obs(13000));assert.equal(db.prepare('SELECT count(*) n FROM track_observations WHERE track_id=?').get(b.id).n,1);assert.equal(tracks(db,'bob')[0].baseline,13000);assert.equal(tracks(db,'bob')[0].lowest,13000);db.close();});
test('one product failure does not stop another product',async()=>{const db=setup(),a=verified(db);const other=obs();other.productId='other';other.variantId='other';other.signals=other.signals.map(s=>({...s,productId:'other',variantId:'other'}));const b=verified(db,'bob',other);db.prepare('UPDATE products SET next_check=0').run();let n=0;await tick(db,async()=>{n++;if(n===1)throw new Error('failure');return other;});assert.equal(n,2);assert.ok(db.prepare('SELECT last_check FROM products WHERE id=?').get(b.productId).last_check>0);assert.equal(tracks(db,'alice')[0].current,10000);db.close();});
