import {test} from 'node:test';import assert from 'node:assert/strict';
import {openDB,addVerifiedTrack,record} from '../src/db.js';import {register,login,session,authenticate} from '../src/auth.js';
import {loadGmail,sendVerification,verifyAddress,mailSettings,saveMailSettings,requestEmailReset,finishEmailReset} from '../src/email.js';import {deliverOutbox,saleMessage} from '../src/notifications.js';
async function setup(){const db=openDB(':memory:');const u=await register(db,{email:'owner@example.com',password:'correct-horse-password'});const messages=[];const transport={sendMail:async m=>{messages.push(m);return {accepted:[m.to.address]};}};const mailer=loadGmail(db,{config:{enabled:true,address:'sender@gmail.com',appPassword:'abcdefghijklmnop'},transport});return {db,u,messages,mailer};}
const code=m=>m.text.match(/\b\d{8}\b/)[0];
test('recipient verification, preferences and email password reset revoke old sessions',async()=>{const {db,u,messages,mailer}=await setup();assert.equal(mailSettings(db,u.id).verified,false);assert.throws(()=>saveMailSettings(db,u.id,{enabled:true,minPercent:0}),/Verify/);await sendVerification(db,mailer,u.id,'owner@example.com');assert.throws(()=>verifyAddress(db,u.id,'00000000'));verifyAddress(db,u.id,code(messages[0]));assert.throws(()=>verifyAddress(db,u.id,code(messages[0])));saveMailSettings(db,u.id,{enabled:true,minPercent:10});assert.equal(mailSettings(db,u.id).enabled,true);const old=session(db,u.id);await requestEmailReset(db,mailer,'owner@example.com');await finishEmailReset(db,'owner@example.com',code(messages[1]),'new-correct-horse-password');assert.equal(authenticate(db,'sw_session='+old.token),null);assert.equal(await login(db,{email:'owner@example.com',password:'new-correct-horse-password'}),u.id);await assert.rejects(finishEmailReset(db,'owner@example.com',code(messages[1]),'another-good-password'));db.close();});
test('verification attempts and expiry are enforced',async()=>{const {db,u,messages,mailer}=await setup();await sendVerification(db,mailer,u.id,'other@example.com');for(let i=0;i<5;i++)assert.throws(()=>verifyAddress(db,u.id,'00000000'));assert.throws(()=>verifyAddress(db,u.id,code(messages[0])));await sendVerification(db,mailer,u.id,'other@example.com');db.prepare('UPDATE mail_codes SET expires=0').run();assert.throws(()=>verifyAddress(db,u.id,code(messages[1])));db.close();});
test('SMTP duplicate requests and unknown delivery are never sent twice',async()=>{const {db,mailer,messages}=await setup();const m={idempotencyKey:'test-id',to:'recipient@example.com',subject:'test',text:'test'};assert.equal((await mailer.send(m)).accepted,true);await mailer.send(m);assert.equal(messages.length,1);let calls=0;const failing=loadGmail(db,{config:{enabled:true,address:'sender@gmail.com',appPassword:'abcdefghijklmnop'},transport:{sendMail:async()=>{calls++;throw Error('timeout after submission');}}});assert.equal((await failing.send({...m,idempotencyKey:'unknown'})).accepted,false);await failing.send({...m,idempotencyKey:'unknown'});assert.equal(calls,1);db.close();});
test('rolling daily cap rejects the 81st email without network or automatic charges',async()=>{const {db,mailer,messages}=await setup();for(let i=0;i<80;i++)await mailer.send({idempotencyKey:String(i),to:'recipient@example.com',subject:'test',text:'test'});assert.equal((await mailer.send({idempotencyKey:'81',to:'recipient@example.com'})).deferred,true);assert.equal(messages.length,80);db.close();});
test('password reset does not send to an unverified account address',async()=>{const {db,u,messages,mailer}=await setup();await requestEmailReset(db,mailer,'owner@example.com');await requestEmailReset(db,mailer,'missing@example.com');assert.equal(messages.length,0);db.close();});
test('confirmed drops reach verified recipients once and preference filters work',async()=>{const {db,u,messages,mailer}=await setup();await sendVerification(db,mailer,u.id,'owner@example.com');verifyAddress(db,u.id,code(messages[0]));saveMailSettings(db,u.id,{enabled:true,minPercent:20});const o={state:'VERIFIED',retailer:'lisa-gozlan',productId:'1',variantId:'2',seller:'Lisa Gozlan',currency:'CAD',available:true,title:'Bracelet',variant:'Gold',cents:10000,signals:[{source:'json',kind:'selling-price',productId:'1',variantId:'2',currency:'CAD',cents:10000}]};const p=addVerifiedTrack(db,u.id,{url:'https://www.lisagozlan.com/products/bracelet?variant=2'},o);record(db,p.productId,o,1000);const drop=n=>({...o,cents:n,signals:o.signals.map(s=>({...s,cents:n}))});record(db,p.productId,drop(9000),2000);record(db,p.productId,drop(9000),2400);await deliverOutbox(db,mailer);assert.equal(messages.length,1);assert.equal(db.prepare('SELECT status FROM outbox').get().status,'FILTERED');record(db,p.productId,drop(6000),3000);record(db,p.productId,drop(6000),3400);await deliverOutbox(db,mailer);await deliverOutbox(db,mailer);assert.equal(messages.length,2);assert.match(messages[1].text,/60\.00/);assert.equal(messages[1].to.address,'owner@example.com');db.close();});
test('custom images become inline attachments without filesystem reads',()=>{const m=saleMessage({title:'A',retailer:'B',variant:'C',url:'https://example.com',old:100,new:50,image:'data:image/png;base64,aGVsbG8='});assert.equal(m.attachments[0].cid,'product-image');assert.match(m.html,/cid:product-image/);assert.equal(m.attachments[0].content.toString(),'hello');});
