import {test} from 'node:test';import assert from 'node:assert/strict';import {parseGarage,embeddedObject} from '../src/adapters/garage.js';
const url='https://www.garageclothing.com/ca/p/hoodie/123ABC.html?dwvar_123ABC_size=S%2FM';
function fixture(){return {p:{productName:'Hoodie',masterProductId:'123',variationGroupId:'123ABC',pid:'SKU1',hasLengths:false,colors:{selected:{variationGroupId:'123ABC',displayValue:'Green'}},sizes:{selected:{displayValue:'S/M',selectable:true,variantIds:['SKU1']},values:[{displayValue:'S/M',selectable:true},{displayValue:'L/XL',selectable:false}]},isSkuSelected:true,isOutOfStockItem:false,isEarlyAccess:false,showLoyaltyPrice:false,price:{finalPriceRaw:79.95,salePrice:'$79.95',showPromoPrice:false}},o:{'@type':'Product','@id':'https://www.garageclothing.com/ca/p/hoodie/SKU1.html',sku:'SKU1',color:'Green',offers:{priceCurrency:'CAD',price:'79.95',availability:'http://schema.org/InStock',shippingDetails:{shippingDestination:{addressCountry:'CA'}}}}};}
const html=f=>`<html lang="en-CA"><script>window.DATA={'stores': ${JSON.stringify({pdp:f.p})}};</script><script type="application/ld+json">${JSON.stringify(f.o)}</script>`;
test('Garage exact SKU, colour, size and selling-price signals agree',()=>{const r=parseGarage(html(fixture()),url);assert.equal(r.state,'VERIFIED');assert.equal(r.cents,7995);assert.equal(r.variantId,'SKU1');assert.equal(r.variant,'Green / S/M');});
test('Garage size-less links require selection',()=>{const r=parseGarage(html(fixture()),url.split('?')[0]);assert.equal(r.state,'UNCERTAIN');assert.equal(r.variantParam,'dwvar_123ABC_size');assert.equal(r.variants.length,2);});
for(const [name,mutate] of [
 ['wrong size',f=>f.p.sizes.selected.displayValue='L/XL'],['wrong colour',f=>f.o.color='Blue'],['wrong product',f=>f.p.variationGroupId='other'],['wrong SKU',f=>f.o.sku='other'],['sold out',f=>f.p.isOutOfStockItem=true],['unavailable size',f=>f.p.sizes.selected.selectable=false],['no exact selection',f=>f.p.isSkuSelected=false],['length required',f=>f.p.hasLengths=true],['loyalty price',f=>f.p.showLoyaltyPrice=true],['promotion',f=>f.p.price.showPromoPrice=true],['early access',f=>f.p.isEarlyAccess=true],['USD',f=>f.o.offers.priceCurrency='USD'],['US delivery',f=>f.o.offers.shippingDetails.shippingDestination.addressCountry='US'],['source conflict',f=>f.o.offers.price='49.95'],['zero',f=>{f.p.price.finalPriceRaw=0;f.p.price.salePrice='$0.00';f.o.offers.price='0';}],['financing',f=>f.p.price.finalPriceRaw=13.33],['wrong offer identity',f=>f.o['@id']='https://evil.test/SKU1.html']
])test('Garage rejects '+name,()=>{const f=fixture();mutate(f);assert.equal(parseGarage(html(f),url).state,'UNCERTAIN');});
test('Garage missing and duplicate evidence fail closed',()=>{const f=fixture();assert.equal(parseGarage('<html lang="en-CA">',url).state,'UNCERTAIN');assert.equal(parseGarage(html(f)+html(f),url).state,'UNCERTAIN');});
test('Garage regular and clearance prices never use crossed-out list price',()=>{const f=fixture();f.p.price.listPrice='$150.00';f.p.price.finalPriceRaw=39.95;f.p.price.salePrice='$39.95';f.o.offers.price='39.95';assert.equal(parseGarage(html(f),url).cents,3995);});
test('embedded JSON handles escaped quotes and braces without executing code',()=>{assert.deepEqual(embeddedObject('{"a":"brace } and \\\" quote","b":{"c":1}};throw Error()',0),{a:'brace } and " quote',b:{c:1}});assert.throws(()=>embeddedObject('{"a":1',0));});
test('Garage regular price comes from the verified selected SKU, never replaces selling price',()=>{const f=fixture();f.p.price.listPrice='$99.95';const r=parseGarage(html(f),url);assert.equal(r.regularCents,9995);assert.equal(r.cents,7995);assert.equal(r.regularSignals[0].variantId,'SKU1');});
