import {test} from 'node:test';import assert from 'node:assert/strict';import {parseHollister,cadAmount} from '../src/adapters/hollister.js';
const url='https://www.hollisterco.com/shop/ca/p/tee-123?sw_sku=456';
function fixture(){const p={productId:'123',productName:'Tee',swatchName:'Blue',isAppExclusive:false},sku={productId:'123',shortSku:'456',fullSizeLabel:'S X Regular',inventoryStatus:'Available',inventory:5,preOrderEligible:false,prices:{list:{originalPrice:'$44.95 CAD',discountPrice:''}}};return {data:{country:'CA',currency:'CAD',store:'h-ca',productId:'123',CACHE:{ROOT_QUERY:{x:{collectionApiSuccess:true,collection:{siteRegion:'CA',products:[p],skus:[sku]}}}}},legacy:{productId:'123',items:{'456':{offerPrice:44,offerPriceFmt:'$44.95&nbsp;CAD'}}}};}
const html=f=>`<script>productPrices[123] = ${JSON.stringify(f.legacy)};window['APOLLO_STATE__product-mfe-web-service-ProductPageFrontend-config'] = ${JSON.stringify(f.data)};</script>`;
test('Hollister exact SKU full-precision CAD amounts resolve truncated legacy dollars',()=>{assert.equal(parseHollister(html(fixture()),url).cents,4495);assert.equal(cadAmount('$44.95 USD'),null);assert.equal(cadAmount('$0.00 CAD'),null);});
test('Hollister missing size offers exact choices',()=>{assert.equal(parseHollister(html(fixture()),url.split('?')[0]).variants[0].id,'456');});
for(const [name,mutate]of [['currency',f=>f.data.currency='USD'],['country',f=>f.data.country='US'],['product',f=>f.data.productId='999'],['SKU',f=>f.data.CACHE.ROOT_QUERY.x.collection.skus[0].shortSku='999'],['sold out',f=>f.data.CACHE.ROOT_QUERY.x.collection.skus[0].inventory=0],['preorder',f=>f.data.CACHE.ROOT_QUERY.x.collection.skus[0].preOrderEligible=true],['conflicting prices',f=>f.legacy.items['456'].offerPriceFmt='$34.95 CAD'],['unexplained numeric difference',f=>f.legacy.items['456'].offerPrice=12],['app exclusive',f=>f.data.CACHE.ROOT_QUERY.x.collection.products[0].isAppExclusive=true]])test('Hollister rejects '+name,()=>{const f=fixture();mutate(f);assert.equal(parseHollister(html(f),url).state,'UNCERTAIN');});
test('Hollister sale uses matching exact SKU discount not list price',()=>{const f=fixture();f.data.CACHE.ROOT_QUERY.x.collection.skus[0].prices.list.discountPrice='$29.95 CAD';f.legacy.items['456']={offerPrice:29,offerPriceFmt:'$29.95 CAD'};assert.equal(parseHollister(html(f),url).cents,2995);});

function grouped(){const f=fixture();const p=f.data.CACHE.ROOT_QUERY.x.collection.products[0];p.productPageUrl='/shop/ca/p/hoodie-999?seq=15';p.defaultSwatchSequence='15';return f;}
const groupUrl='https://www.hollisterco.com/shop/ca/p/hoodie-999?seq=15&sw_sku=456';
test('Hollister catalogue group URL resolves its exact selected colour and SKU',()=>{const r=parseHollister(html(grouped()),groupUrl);assert.equal(r.state,'VERIFIED');assert.equal(r.productId,'123');assert.equal(r.variantId,'456');});
test('Hollister catalogue group offers sizes before saving',()=>{assert.equal(parseHollister(html(grouped()),groupUrl.replace('&sw_sku=456','')).variants[0].id,'456');});
for(const [name,mutate]of [['wrong colour sequence',p=>p.defaultSwatchSequence='14'],['different group page',p=>p.productPageUrl='/shop/ca/p/hoodie-888?seq=15'],['foreign origin',p=>p.productPageUrl='https://example.com/shop/ca/p/hoodie-999?seq=15'],['missing group evidence',p=>delete p.productPageUrl]])test('Hollister group rejects '+name,()=>{const f=grouped();mutate(f.data.CACHE.ROOT_QUERY.x.collection.products[0]);assert.equal(parseHollister(html(f),groupUrl).state,'UNCERTAIN');});

test('Hollister lists all bound colour links and omits foreign pages',()=>{const f=grouped(),c=f.data.CACHE.ROOT_QUERY.x.collection;c.products.push({...c.products[0],productId:'124',swatchName:'Red',defaultSwatchSequence:'16',productPageUrl:'/shop/ca/p/hoodie-999?seq=16'},{...c.products[0],productId:'125',defaultSwatchSequence:'17',productPageUrl:'https://example.com/shop/ca/p/hoodie-999?seq=17'});const r=parseHollister(html(f),groupUrl);assert.deepEqual(r.colours.map(c=>c.id),['15','16']);assert.equal(r.selectedColour,'15');assert.equal(r.variants[0].size,'S');assert.equal(r.variants[0].length,'Regular');});
test('Hollister unknown inventory keeps colour and size controls without claiming sold out',()=>{const f=grouped();f.data.CACHE.ROOT_QUERY.x.collection.skus[0].inventory=0;const r=parseHollister(html(f),groupUrl);assert.equal(r.state,'UNCERTAIN');assert.match(r.reason,/Availability unknown/);assert.equal(r.variants[0].availability,'unknown');assert.equal(r.colours.length,1);assert.equal(r.selectedVariant,'456');});
test('Hollister missing secondary SKU price is distinguished from stock failure',()=>{const f=grouped();delete f.legacy.items['456'];const r=parseHollister(html(f),groupUrl);assert.match(r.reason,/Price evidence is missing/);assert.equal(r.variants[0].available,true);});

test('Hollister whole-dollar CAD sale prices verify without requiring .00',()=>{const f=fixture();f.data.CACHE.ROOT_QUERY.x.collection.skus[0].prices.list.discountPrice='$25 CAD';f.legacy.items['456']={offerPrice:25,offerPriceFmt:'$25&nbsp;CAD'};assert.equal(parseHollister(html(f),url).cents,2500);assert.equal(cadAmount('$25\u00a0CAD'),2500);assert.equal(cadAmount('$1,250 CAD'),125000);});
test('Hollister rejects malformed or wrong-currency whole-dollar prices',()=>{for(const v of ['$25 USD','$25','$25.5 CAD','$0 CAD','$-25 CAD','$25.000 CAD'])assert.equal(cadAmount(v),null);const f=fixture();f.data.CACHE.ROOT_QUERY.x.collection.skus[0].prices.list.discountPrice='$25 CAD';f.legacy.items['456']={offerPrice:26,offerPriceFmt:'$26 CAD'};assert.equal(parseHollister(html(f),url).state,'UNCERTAIN');});
test('Hollister regular price joins both list-price signals for the selected SKU',()=>{const f=fixture();f.data.CACHE.ROOT_QUERY.x.collection.skus[0].prices.list.discountPrice='$37 CAD';f.legacy.items['456']={offerPrice:37,offerPriceFmt:'$37 CAD',listPrice:44,listPriceFmt:'$44.95 CAD'};const r=parseHollister(html(f),url);assert.equal(r.regularCents,4495);assert.equal(r.cents,3700);f.legacy.items['456'].listPriceFmt='$49.95 CAD';assert.equal(parseHollister(html(f),url).regularCents,undefined);});
