import {test} from 'node:test';import assert from 'node:assert/strict';import {parseIndigo} from '../src/adapters/indigo.js';
function fixture(){const url='https://www.indigo.ca/products/book';return {j:{id:123,handle:'book',title:'Book',variants:[{id:456,sku:'9781459823204',title:'Board book',price:1095,available:true,requires_shipping:true}]},g:{'@type':'ProductGroup',url,productGroupID:'123',category:'Book',hasVariant:[{url:url+'?variant=456',sku:'9781459823204',gtin13:'9781459823204',offers:{url:url+'?variant=456',price:10.95,priceCurrency:'CAD',availability:'https://schema.org/InStock',itemCondition:'https://schema.org/NewCondition'}}]}};}
const html=f=>`Shopify.country = "CA"; Shopify.currency = {"active":"CAD"};<script type="application/ld+json">${JSON.stringify(f.g)}</script>`;
test('Indigo joins exact physical edition ISBN and CAD price',()=>{const f=fixture();assert.equal(parseIndigo(html(f),f.j,'456','book').cents,1095);assert.equal(parseIndigo(html(f),f.j,null,'book').variants.length,1);});
for(const [name,mutate]of [['subscription',f=>f.j.variants[0].requires_selling_plan=true],['ISBN mismatch',f=>f.g.hasVariant[0].gtin13='9781459823228'],['USD',f=>f.g.hasVariant[0].offers.priceCurrency='USD'],['used edition',f=>f.g.hasVariant[0].offers.itemCondition='https://schema.org/UsedCondition'],['unavailable',f=>f.j.variants[0].available=false],['price conflict',f=>f.g.hasVariant[0].offers.price=8.99],['wrong group',f=>f.g.productGroupID='999'],['missing evidence',f=>f.g.hasVariant=[]],['duplicate edition',f=>f.g.hasVariant.push({...f.g.hasVariant[0]})],['zero',f=>{f.j.variants[0].price=0;f.g.hasVariant[0].offers.price=0;}]])test('Indigo rejects '+name,()=>{const f=fixture();mutate(f);assert.equal(parseIndigo(html(f),f.j,'456','book').state,'UNCERTAIN');});
function merchandise(){const f=fixture();f.j.type='GM';f.j.variants[0].sku='882709977988';f.j.variants[0].barcode='882709977988';f.g.category='GM';const p=f.g.hasVariant[0];p.sku='882709977988';delete p.gtin13;p.gtin12='882709977988';return f;}
test('Indigo supports exact UPC merchandise without a book ISBN',()=>{const f=merchandise();assert.equal(parseIndigo(html(f),f.j,'456','book').state,'VERIFIED');});
test('Indigo supports single-product JSON-LD and automatically selects its sole option',()=>{const f=merchandise();f.g={...f.g.hasVariant[0],'@type':'Product',url:'https://www.indigo.ca/products/book',category:'GM'};assert.equal(parseIndigo(html(f),f.j,null,'book').variantId,'456');});
test('Indigo refuses ambiguous multi-option single-product evidence',()=>{const f=merchandise();f.g={...f.g.hasVariant[0],'@type':'Product',url:'https://www.indigo.ca/products/book'};f.j.variants.push({...f.j.variants[0],id:457});assert.equal(parseIndigo(html(f),f.j,'456','book').state,'UNCERTAIN');});
test('Indigo digital SKU can differ from ISBN when exact SKU and variant URLs agree',()=>{const f=fixture(),v=f.j.variants[0];v.requires_shipping=false;v.sku='digital-edition-id';v.barcode=v.sku;f.g.hasVariant[0].sku=v.sku;assert.equal(parseIndigo(html(f),f.j,'456','book').state,'VERIFIED');});
for(const [name,mutate]of [['foreign offer',f=>f.g.hasVariant[0].offers.url='https://example.com/products/book?variant=456'],['different variant offer',f=>f.g.hasVariant[0].offers.url='https://www.indigo.ca/products/book?variant=999'],['different UPC',f=>f.g.hasVariant[0].gtin12='111111111111'],['foreign seller',f=>f.g.hasVariant[0].offers.seller={name:'Other seller'}],['expired offer',f=>f.g.hasVariant[0].offers.priceValidUntil='2000-01-01'],['duplicate variant id',f=>f.j.variants.push({...f.j.variants[0]})],['category mismatch',f=>f.g.category='Book']])test('Indigo merchandise rejects '+name,()=>{const f=merchandise();mutate(f);assert.equal(parseIndigo(html(f),f.j,'456','book').state,'UNCERTAIN');});
test('Indigo handles encoded product names and collection links without encoded path traversal',async()=>{const {indigoHandle}=await import('../src/adapters/indigo.js');assert.equal(indigoHandle('/products/lego%C2%AE-rocking-plants-11506'),'lego®-rocking-plants-11506');assert.equal(indigoHandle('/collections/toys/products/lego%C2%AE-rocking-plants-11506'),'lego®-rocking-plants-11506');assert.equal(indigoHandle('/products/a%2Fb'),null);assert.equal(indigoHandle('/products/%2E%2E'),null);assert.equal(indigoHandle('/products/%ZZ'),null);});
test('Auto-selected Indigo option is pinned in server-owned preview and saved URL',async()=>{const {createApp}=await import('../src/server.js'),{openDB}=await import('../src/db.js');const db=openDB(':memory:'),origin='http://127.0.0.1:4197',f=merchandise(),server=createApp({db,origin,inspector:async()=>parseIndigo(html(f),f.j,null,'book')});await new Promise(r=>server.listen(4197,'127.0.0.1',r));try{const registration=await fetch(origin+'/api/register',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({email:'indigo-pin@example.com',password:'test-only-strong-password'})}),auth=await registration.json();const headers={Origin:origin,'Content-Type':'application/json',Cookie:registration.headers.get('set-cookie').split(';')[0],'X-CSRF-Token':auth.csrf};const preview=await(await fetch(origin+'/api/inspect',{method:'POST',headers,body:JSON.stringify({url:'https://www.indigo.ca/products/book'})})).json();assert.equal(preview.state,'VERIFIED');assert.equal(new URL(preview.url).searchParams.get('variant'),'456');const saved=await fetch(origin+'/api/products',{method:'POST',headers,body:JSON.stringify({previewToken:preview.previewToken})});assert.equal(saved.status,201);assert.equal(new URL(db.prepare('SELECT url FROM products').get().url).searchParams.get('variant'),'456');}finally{await new Promise(r=>server.close(r));db.close();}});
test('Indigo exposes exact variant compare-at price separately from its current price',()=>{const f=fixture();f.j.variants[0].compare_at_price=1495;const r=parseIndigo(html(f),f.j,'456','book');assert.equal(r.regularCents,1495);assert.equal(r.cents,1095);});
